services:
  postgres-dev:
    container_name: postgres-dev
    image: postgres:16.0-alpine3.18
    env_file:
      - .env
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
