services:
  postgres-test:
    container_name: postgres-test
    image: postgres:16.0-alpine3.18
    env_file:
      - .env.test
    ports:
      - '5434:5432'
    volumes:
      - postgres-test-data:/var/lib/postgresql/data

volumes:
  postgres-test-data:
